### ISSUE TITLE
Checking datatype using typeof under if condition

### ISSUE THREAD

**Issue by RaviAnand** [training-jyas/javascript-weekend-batch-2#5]
var b;

function fn(a) {
	console.log(typeof a);
	if(a !== null && a !== undefined && a !== NaN && a !== String){
//It is not validating for String and NaN as it enter into the if condition even if we pass String or NaN.
		
		console.log("a is a number", a);

		b= a*10;
		return b;
		
	}
	else {
		return a;
	}
	
	
}
var c = fn("abc");
console.log(c);

**Comment by jyasveer** [comment]
var b;

function fn(a) {
    console.log(typeof a);
    console.log(String);
    if (a !== null && a !== undefined && a !== NaN && typeof a !== 'string') {
        //It is not validating for String and NaN as it enter into the if condition even if we pass String or NaN.

        console.log("a is a number", a);

        b = a * 10;
        return b;

    } else {
        return a;
    }
}
var c = fn("abc");
console.log(c);
